openapi: 3.0.3
info:
  title: new-api
  description: new api
  termsOfService: ''
  contact:
    email: ''
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '0.1'
externalDocs:
  description: Find out more about spec
  url: ''
servers: []
tags:
  - name: Default
    description: ''
paths: {}
components:
  schemas: {}
  securitySchemes: {}
